### ISSUE TITLE
Building problems by using add_subdirectory

### ISSUE THREAD

**Issue by Febbe** [HDFGroup/hdf5#1]
It is not possible to build against hdf5 when the lib is added with add_subdirectory. The header file H5pubconf.h can not be found the include_dirs.
All generated header files with public visibility should be configured into an extra directory like `${CMAKE_CURRENT_BUILD_DIR}/generated/h5` and this dir should be included with 
```
target_include_directories(mylib PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_BUILD_DIR}/generated>
  $<INSTALL_INTERFACE:include/mylib>  # <prefix>/include/mylib
)
```

**Comment by alephpiece** [comment]
Is it possible to use hdf5 targets in CMake? I didn't find a manual anywhere (for 1.10.5). I have to add include directories and link libraries to my target by myself because I don't know what target I could use. 

If hdf5 is included as a subproject, there will be two targets, hdf5-shared and hdf5-static, but it seems that these targets marked their include directories as private. I have to extract those directories from hdf5 targets.

Is there a simple way to link hdf5 libraries in a CMake file?
```
find_package(HDF5 1.10.5 QUIET COMPONENTS C)
if (HDF5_FOUND)
    
    target_include_directories(my_target INTERFACE ${HDF5_INCLUDE_DIRS})
    target_compile_definitions(my_target INTERFACE ${HDF5_DEFINITIONS})
    target_link_libraries(my_target INTERFACE ${HDF5_LIBRARIES})

else ()

    config_hdf5()
    add_subdirectory(hdf5)

    target_include_directories(my_target INTERFACE $<TARGET_PROPERTY:hdf5-shared,INCLUDE_DIRECTORIES>)
    target_link_libraries(my_target INTERFACE hdf5-shared)
    add_dependencies(my_target hdf5-shared)

endif()
```

**Comment by tueda** [comment]
While [hdf5-1_12_0](https://github.com/HDFGroup/hdf5/releases/tag/hdf5-1_12_0) doesn't work with the following `CMakeLists.txt` using `add_subdirectory` to add HDF5 (because of `H5pubconf.h`), the current development version (9df906126f5d448ad52a98ba99fd2eb2f4b4f5eb) seems to work (at least, for simple C examples):
```
cmake_minimum_required(VERSION 3.12)

project(test1 C)

set(HDF5_EXTERNALLY_CONFIGURED 1)
set(BUILD_TESTING OFF CACHE BOOL "Build HDF5 Unit Testing")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build Shared Libraries")
set(HDF5_BUILD_CPP_LIB OFF CACHE BOOL "Build HDF5 C++ Library")
set(HDF5_BUILD_HL_LIB OFF CACHE BOOL "Build HIGH Level HDF5 Library")
set(HDF5_BUILD_TOOLS OFF CACHE BOOL "Build HDF5 Tools")
set(HDF5_BUILD_EXAMPLES OFF CACHE BOOL "Build HDF5 Library Examples")
add_subdirectory(extern/hdf5)

add_executable(test1 test1.c)
target_link_libraries(test1 PRIVATE hdf5-static)
```

A problem I found is that when I modify `CMakeLists.txt` all the C sources of `hdf5-static` are always recompiled, which takes a non-negligible time.

**Comment by tueda** [comment]
For reference for those who hit this issue: I have realized there are related posts in the forum,
- [Issues when using HDF5 as a git submodule and using CMake with add_subdirectory](https://forum.hdfgroup.org/t/issues-when-using-hdf5-as-a-git-submodule-and-using-cmake-with-add-subdirectory/7189)
- [Issue when building hdf5 as submodule via `add_subdirectory`](https://forum.hdfgroup.org/t/issue-when-building-hdf5-as-submodule-via-add-subdirectory/6990)

The former solved my problem (`hdf5-static`  always recompiled).

**Comment by byrnHDF** [comment]
Proof of working is at https://github.com/HDFGroup/hdf5-examples/pull/49
