### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [HDFGroup/hdf5#1073]
Hey there!

I belong to an open source security research community, and a member (@zanderhuang) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by epourmal** [comment]
Hello!

Please send email to help@hdfgroup.org and we will go from there. We will take a look at SECURITY.md file.

Thank you for investigating and for bringing the issue to our attention!

Elena

**Comment by JamieSlome** [comment]
@epourmal - great, thanks!

You should have received multiple e-mails from us yesterday! ❤️

**Comment by ZanderHuang** [comment]
Sorry for the late reply, I realized some issues in the reports
1. crash line number does not match due to some modifications made in my local code version.  
2. Description error caused by markdown grammar.
The issues mentioned above have been resolved.  
I also refined the description and resubmitted the reports.

Please refer to the links below for the updated reports:
1. https://www.huntr.dev/bounties/4460b820-60fc-451d-baa6-2c8c6c7c1441/
2. https://www.huntr.dev/bounties/84eaa6f1-2e7f-4741-b3a9-62a0a62a2a91/
3. https://www.huntr.dev/bounties/806d0b78-f11c-4dd5-b138-752dce4afb4d/
4. https://www.huntr.dev/bounties/26d9ccfc-39b0-47ff-83c7-e995e2bba8b5/

If you require any further information, please drop me an email at wenjiezander@gmail.com
