### ISSUE TITLE
can I turn off lock function?

### ISSUE THREAD

**Issue by yixingzhong** [HDFGroup/hdf5#1323]
when it reads different hdf5 files,also need wait other thread haved done read hdf5 file. I try to to turn off lock,but threads read fail. why do use lock function when read different hdf5 files?

**Comment by derobins** [comment]
Questions about how to use HDF5 should be asked on the forum:

https://forum.hdfgroup.org/

As for the file locking, the scheme was added in HDF5 1.10.0 when we added single-writer/multiple-reader (SWMR) support. Since we were now explicitly telling people it was okay to open files that were being written to (in certain circumstances), we added file locking as a protection mechanism to prevent inappropriate access that could cause a reader to crash.
