### ISSUE TITLE
h5perf conflicts with gnu/perf tool

### ISSUE THREAD

**Issue by bartoszek** [HDFGroup/hdf5#1787]
`perf` is a quite unlucky choice of name for this small tool, especially on Unix target: as the common profiling tool `gnu/perf` conflict with `hdf5` package when built with `openmpi` support enabled. 
https://github.com/HDFGroup/hdf5/blob/a124f02f2c94476f58e4bca047e7786a3231cf0c/tools/src/h5perf/CMakeLists.txt#L33-L39
https://github.com/HDFGroup/hdf5/blob/a124f02f2c94476f58e4bca047e7786a3231cf0c/tools/src/h5perf/Makefile.am#L24-L29

**Comment by jedbrown** [comment]
This is really disruptive because many HDF5 users also use `perf` for profiling. Lack of an upstream fix means that packagers for each distribution will be making their own work-arounds and this divergence will create a poor user experience and support thicket. HDF5 maintainers: if you lack the time to fix right now, can you please comment here with your preferred name so packagers can rename consistently until an upstream fix arrives?

**Comment by derobins** [comment]
perf is a separate tool from h5perf. It's a very old legacy program from the early days of HDF5 that doesn't do much.

I'm in the process of removing perf entirely so we'll be able to close this soon. The fix will be in 1.13.2 and 1.10.10. h5perf and h5perf_serial will remain.

I'll also try to remove perf from 1.8 and 1.12 so the last releases around the end of this year / early next year will also be fixed.

**Comment by jedbrown** [comment]
Thank you! This appears to have been added in f8ecdf846c7e054d874ea92baf5c9b6c2b47e836, between 1.12.1 and 1.12.2. The reason many people are complaining is because it was new in 1.12.2 (from their perspective). This may make it simpler for you to remove where relevant.
```console
$ git grep 'bin_PROGRAMS=.*perf' hdf5-1_12_1
hdf5-1_12_1:tools/test/perform/Makefile.am:    bin_PROGRAMS=h5perf_serial h5perf
hdf5-1_12_1:tools/test/perform/Makefile.am:    bin_PROGRAMS=h5perf_serial
$ git grep 'bin_PROGRAMS=.*perf' hdf5-1_12_2
hdf5-1_12_2:tools/src/h5perf/Makefile.am:    bin_PROGRAMS=h5perf_serial perf h5perf
hdf5-1_12_2:tools/src/h5perf/Makefile.am:    bin_PROGRAMS=h5perf_serial
```
The corresponding CMake file moved from tools/test/perform to tools/src/h5perf.
```console
$ git grep 'add_executable.*\bperf\b' hdf5-1_12_1
hdf5-1_12_1:tools/test/perform/CMakeLists.txt:    add_executable (perf ${perf_SOURCES})
$ git grep 'add_executable.*\bperf\b' hdf5-1_12_2
hdf5-1_12_2:tools/src/h5perf/CMakeLists.txt:    add_executable (perf ${perf_SOURCES})
```

**Comment by derobins** [comment]
This has been merged to develop and I'll propagate it around this week.

Note that 1.12.1 and 1.12.2 won't be updated.
