### ISSUE TITLE
Reading subset from S3 compatible storage Minio cluster, very low speed 

### ISSUE THREAD

**Issue by GurSergey** [HDFGroup/hdf5#1792]
Hi! i am trying to read subset from Minio single instance and from cluster using following command:
h5dump --filedriver=ros3 -d "statistics" --start="0,0,0" --count="960,2000,1" --output=test.txt http://localhost:9000/raw/test.hdf5
Test file contains 700 MB data. The requested subset contains about 7 MB of data
Result: 
1. Reading time from Minio single instance ≈11 seconds
2. Reading time from Minio cluster  ≈12 minute 10 seconds

I conducted this experiment on different clusters, in different configurations, but the result is the same
You have  any idea why reading from a cluster is so slow? it should be faster than reading from a single instance

**Comment by derobins** [comment]
Hi, sorry to get to this so late, but we don't really handle help requests on GitHub. If this is still a concern, please ask your questions on the HDF Group forum (https://forum.hdfgroup.org/).

I'm not familiar with Minio, but if it behaves like AWS's S3, you should watch one of our talks on cloud-optimized HDF5.

https://www.youtube.com/watch?v=rcS5vt-mKok
https://www.youtube.com/watch?v=8Vh-BkahMzw

It's also helpful to update to the latest version of HDF5, since we've been making improvements to the ros3 VFD.
