### ISSUE TITLE
feature/multi_dataset - failed when data type conversions are interleaved

### ISSUE THREAD

**Issue by wkliao** [HDFGroup/hdf5#1859]
I am testing the multi-dataset feature using the [E3SM I/O pattern](https://github.com/Parallel-NetCDF/E3SM-IO) and encountered an error. The error occurs when writing multiple datasets and data type conversion is required for some datasets. To reproduce the problem, I modified the test program `testpar/t_pmulti_dset.c` as below.
```
  diff --git a/testpar/t_pmulti_dset.c b/testpar/t_pmulti_dset.c
  index f710f6a8..f6487956 100644
  --- a/testpar/t_pmulti_dset.c
  +++ b/testpar/t_pmulti_dset.c
  @@ -250,7 +250,8 @@ test_pmdset(size_t niter, unsigned flags)
               } /* end if */
   
               /* Create dataset */
  -            if ((dset_ids[j] = H5Dcreate2(file_id, dset_name[j], H5T_NATIVE_UINT, file_space_ids[j],
  +            hid_t mtype = (j % 2 == 0) ? H5T_NATIVE_UINT : H5T_NATIVE_INT;
  +            if ((dset_ids[j] = H5Dcreate2(file_id, dset_name[j], mtype, file_space_ids[j],
                                             H5P_DEFAULT, dcpl_id, H5P_DEFAULT)) < 0)
                   T_PMD_ERROR
           } /* end for */
```

The error message shown on screen:
```
Configuration:
  Layout:     Contiguous
  Shape same: No
  I/O type:   Multi
  MPI I/O type: Collective
Testing random I/O    t_pmulti_dset: /files2/scratch/wkliao/HDF5/Github/hdf5/src/H5Dscatgath.c:384: H5D__gather_mem: Assertion `nelmts > 0' failed.
Abort (core dumped)
```

**Comment by fortnern** [comment]
This should be fixed now in the feature/multi_dataset branch. Let me know if it works for you

**Comment by fortnern** [comment]
One thing to keep in mind: while datatype conversion works (now), if any of the datasets use datatype conversion you will not see any performance benefit from multi dataset, and it may in fact degrade performance since it will break collective for all datasets and not just the ones with type conversion. You might consider splitting the I/O into two calls: one for datasets with type conversion and one without.

**Comment by wkliao** [comment]
Could you please provide more information on why datasets requiring type conversion will break the collective I/O? Are you implying that each dataset requiring type conversion is using independent I/O internally?

I am using E3SM to test and E3SM writes hundreds of datasets per time step and almost all datasets require type conversion from double to float. I believe this is also the case for many applications that write/read history files.

**Comment by fortnern** [comment]
Type conversion has always broken collective I/O in HDF5. This is because it would require a separate implementation due to the need for a type conversion buffer (and possibly a background buffer and all the complications that come with that). I believe it would be possible to do this but I don't recall ever hearing about a demand for it. We can certainly look into it though.

**Comment by fortnern** [comment]
Yes any I/O with type conversion will use Independent I/O and the associated pathway (which is mostly the same as serial) in the HDF5 library.

**Comment by epourmal** [comment]
Conversion from double to float probably can be done in place. Can this be considered and fixed?

**Comment by qkoziol** [comment]
> Conversion from double to float probably can be done in place. Can this be considered and fixed?

This would modify the user's buffer, and would require them to opt-in to this data-destructive behavior (with a new property).

**Comment by epourmal** [comment]
Yes, but at least users would have some control. Now HDF5 uses memory AND breaks collective 😀

**Comment by qkoziol** [comment]
No - right now, it just breaks collective.

**Comment by wkliao** [comment]
If the in-place type conversion modifies the user's buffers, then this option will not work for applications like E3SM which uses the same buffers to continue the simulation. It is important that the contents of the user buffers are not modified, or at least must be restored to the original values after the write completes.

**Comment by wkliao** [comment]
Got an error when a dataset is defined with an unlimited dimension and
written twice in a single call to `H5Dwrite_multi`, each to a separate
extended space. The error occurs only when in collective I/O mode, but
not in independent mode. This time there is no data type conversion.
```
H5Shyper.c:7039: H5S__hyper_adjust_s: Assertion `(hssize_t)space->select.sel_info.hslab->diminfo.opt[u].start >= offset[u]' failed.
```
Here is a short program to reproduce the error,
[h5_multidataset.c](https://github.com/Parallel-NetCDF/E3SM-IO/blob/hdf5_multidataset/tests/h5_multidataset.c)

**Comment by fortnern** [comment]
> Got an error when a dataset is defined with an unlimited dimension and written twice in a single call to `H5Dwrite_multi`, each to a separate extended space. The error occurs only when in collective I/O mode, but not in independent mode. This time there is no data type conversion.
> 
> ```
> H5Shyper.c:7039: H5S__hyper_adjust_s: Assertion `(hssize_t)space->select.sel_info.hslab->diminfo.opt[u].start >= offset[u]' failed.
> ```
> 
> Here is a short program to reproduce the error, [h5_multidataset.c](https://github.com/Parallel-NetCDF/E3SM-IO/blob/hdf5_multidataset/tests/h5_multidataset.c)

I think this is an error in the test program, since the extent of the filespace for the first element is no longer valid after the dataset gets extended in the second iteration of the loop. You could fix this by extending the dataspaces with H5Sset_extent_simple to match the dataset's space, or simply creating them with the final size (if that is known). The main thing is the filespace needs to be correct at the moment H5Dwrite_multi is called.

It shouldn't cause an assertion failure though, I will fix that. Thanks!

**Comment by wkliao** [comment]
I tried both approaches but still got the same error.

Approach 1. Use H5Sset_extent_simple
```
  --- a/tests/h5_multidataset.c
  +++ b/tests/h5_multidataset.c
  @@ -64,6 +64,8 @@ main(int argc, char *argv[])
           ids[i] = dataset;
           mType[i] = H5T_NATIVE_INT;
       }
  +    for (i=0; i<NREQS; i++)
  +        H5Sset_extent_simple(filespace[i], 2, dims, NULL);
   
       /* collective I/O */
       hid_t xfer_plist = H5Pcreate(H5P_DATASET_XFER);
```
Approach 2. Create filespace with the final size
```
  --- a/tests/h5_multidataset.c
  +++ b/tests/h5_multidataset.c
  @@ -44,15 +44,15 @@ main(int argc, char *argv[])
       H5Sclose(dataspace[0]);
       H5Pclose(cparms);
   
  +    /* Extend the dataset */
  +    dims[0] = NREQS;
  +    H5Dset_extent(dataset, dims);
  +
       for (i=0; i<NREQS; i++) {
           hsize_t start[NREQS] = {0, 0};
           hsize_t count[NREQS] = {1, 1};
           hsize_t block[NREQS] = {1, rec_size};
   
  -        /* Extend the dataset */
  -        dims[0] = i+1;
  -        H5Dset_extent(dataset, dims);
  -
           /* Select a hyperslab */
           filespace[i] = H5Dget_space(dataset);
           start[0] = i;
```

**Comment by fortnern** [comment]
Ok after looking into this further I think the library is getting confused because the same dataset is listed twice in the mdset call. Is it important to be able to use the same dataset twice in a single mdset call? It might take some time to get this to work correctly. Otherwise I can potentially check for this condition, though that would involve either building a tree or similar structure for the purpose of this check or an N^2 algorithm.

**Comment by wkliao** [comment]
It will be great if mdset supports multiple entries of the same dataset in a single call.
I believe cache VOL and async I/O VOL are waiting and expecting to use this feature,
something I learned from their developers in a recent conversation. I can certainly
avoid multiple datasets in a single call in the E3SM-IO test case. Without this feature
is not a deal breaker.

I am more eager to see the implementation of using collective I/O mode when type
conversion is required. I think it is a critical solution to make HDF5 performance
comparable with other libraries, given the I/O patterns similar to the E3SM.

**Comment by fortnern** [comment]
Unfortunately I think it would be very difficult to implement full support for passing the same dataset twice to a single multi dataset I/O call due to MPI I/O's requirement for monotonically nondecreasing file offsets. Consider what we need to do if, for example, two instances of the same dataset select different columns in the same chunk. It would be possible for HDF5 to build a list of all contiguous blocks in the I/O request and sort them (essentially doing MPI's job), but this could come at a steep performance/memory cost and we would want to only do this when necessary.

**Comment by wkliao** [comment]
Isn't the same sorting required even when datasets appear only once?
My understanding is the file offsets of data chunks of datasets may be
spread all over the file.

**Comment by fortnern** [comment]
Yes the file blocks must always be sorted by file offset. However, it is much more difficult when the same dataset is present multiple times because selected blocks can be interleaved within the same chunk, necessitating that entire selections be torn down, reshuffled across elements in the dataset array, and rebuilt while transforming the memory selections to match. When each dataset is present only once we need only sort the chunks since the selections are already in file order (with the exception of point selections).

**Comment by fortnern** [comment]
Closing this since the original issue was fixed. If you like you can open a feature request for allowing the same dataset multiple times in a H5Dread/write_multi call, and for collective type conversion (although work on collective type conversion is in progress).
