### ISSUE TITLE
cross-compiling from x86_64-linux-musl to  x86_64-linux-gnu

### ISSUE THREAD

**Issue by Alexander-Barth** [HDFGroup/hdf5#1948]
I am trying to provide a HDF5 binary for julia users. Julia's build tree uses cross-compilation from a  x86_64-linux-musl build environment. 

When compiling HDF5 1.12.2 or current develop branch (33f6ade6e77ed85442f001fa32924127455aca39) to target x86_64-linux-gnu (same architecture/OS but different libc):

```bash
./configure --prefix=/workspace/destdir --build=x86_64-linux-musl --host=x86_64-linux-gnu --enable-shared \
   --disable-static --with-zlib=/workspace/destdir --with-pthread=yes --enable-threadsafe \
   --enable-build-mode=production --enable-using-memchecker --enable-ros3-vfd \
   --enable-unsupported --enable-tests=no
```

I get this error:

```
checking maximum decimal precision for C... configure: error: in `/workspace/srcdir/hdf5-1.12.2':
configure: error: cannot run test program while cross compiling
```

Would it be possible to by-pass this test by e.g. setting an environment variable? I guess that this is the purpose of this patch from conda-forge:
https://github.com/conda-forge/hdf5-feedstock/blob/main/recipe/patches/osx_cross_configure.patch

Reference:
https://github.com/JuliaPackaging/Yggdrasil/issues/4511#issuecomment-1199281217

**Comment by mkitti** [comment]
Once upon a time, @stevengj started a [fork to try to address cross compilation](https://github.com/stevengj/hdf5/commit/6b0545585282647bb8d7be8744d73745b000bdd3) (for Yggdrasil and Julia packaging).

His approach was to use autoconf's cross compilation features. Essentially, the compiler already knows the answers to many of the questions being asked during by these "test programs". Thus rather than executing the test programs, we just have to compile and inspect the resulting machine code.

The idea was to use the `AC_CHECK_SIZEOF` or `AC_COMPUTE_INT` macros to sort this out.
https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Generic-Compiler-Characteristics.html

I don't have much experience with this, but I would be interested in picking this up and pushing it further.

**Comment by derobins** [comment]
Can this issue be closed?

* The long double checks are gone
* AC_RUN_IFELSE in the Autotools has defaults for everything that is left (just szip encoding and checking pthread_attr_setscope)
* H5detect is gone
* H5make_libsettings is gone

Cross compiling should basically just work now

**Comment by mkitti** [comment]
@Alexander-Barth , I think we can close. https://github.com/JuliaPackaging/Yggdrasil/pull/6795 is already operating off the earlier cross compilation efforts.

**Comment by Alexander-Barth** [comment]
yes, thank you @mkitti
