### ISSUE TITLE
[BUG] H5Tget_native_type reshuffle the order of fields for compound type

### ISSUE THREAD

**Issue by wenjuno** [HDFGroup/hdf5#2071]
**Describe the bug**
Instead of keeping the order of the fields in the input compound type based on the offset of each field, H5Tget_native_type reassigns the offset of each field based on the order the fields are inserted into the input compound type. 

**Expected behavior**
I think at least it should keep the ordering of the fields based on offset instead of the order they are inserted. I would love it to keep the original offsets but I guess that's not always feasible if there is no native type of same size for a given non-native type?

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash): 08aebb6d1a
 - OS and version: Linux
 - Compiler and version: GCC 12.2.0
 - Build system (e.g. CMake, Autotools) and version: CMake
 - Any configure options you specified: CPP and Debug
 - MPI library and version (parallel HDF5): N/A

**Additional context**
My test code
```c++
#include <iostream>
#include <H5Cpp.h>

void print_type(const H5::CompType &dtype, const std::string &dtype_name)
{
  std::cout << dtype_name << '\n';
  const int n{dtype.getNmembers()};
  for (int i(0); i < n; ++i)
  {
    const auto name(dtype.getMemberName(i));
    const auto offset(dtype.getMemberOffset(i));
    const auto size(dtype.getMemberDataType(i).getSize());
    std::cout << "name: " << name
              << ", offset: " << offset
              << ", size: " << size << '\n';
  }
}

int main()
{
  H5::CompType dtype{std::size_t(16)};
  dtype.insertMember("b", 8, H5::PredType::NATIVE_INT32);
  dtype.insertMember("a", 0, H5::PredType::NATIVE_INT64);
  print_type(dtype, "Original");
  H5::CompType native(H5Tget_native_type(dtype.getId(), H5T_DIR_ASCEND));
  print_type(native, "Native");
  return 0;
}
```
The output:
```
Original
name: b, offset: 8, size: 4
name: a, offset: 0, size: 8
Native
name: b, offset: 0, size: 4
name: a, offset: 8, size: 8
```
Note the offset of a and b swapped.

**Comment by fortnern** [comment]
I think the intent of H5Tget_native_type when used with compounds is that the layout of the returned type should exactly match that of a c struct, to simplify reading data. Since you cannot (directly) specify offsets in a c struct, we cannot in general preserve user-specified compound offsets, they must match whatever it would be in the struct. I think the most consistent way to determine element ordering is still to use insertion order; trying to divine the user's intent by using the offsets to determine ordering but not offset seems inconsistent and surprising.

If you want direct control over the offsets of compound elements, you shouldn't be using H5Tget_native_type on the compound. You could instead call H5Tget_native_type on each element and insert them into the new compound using the offset you want.
