### ISSUE TITLE
H5T_enum_nameof is inconsistent with other get_name methods

### ISSUE THREAD

**Issue by PhilPJL** [HDFGroup/hdf5#2183]
HDF 1.10.6

`H5A_get_name, H5F_get_name, H5I_get_name `allow me to determine the size of the buffer required by using:

`int len = H5x_get_name(handle, null, 0);`

`H5T_enum_nameof` doesn't allow this and returns an error of 'no name buffer supplied'.

It would make sense to make H5T_enum_nameof have consistent behaviour with other get_name methods.

**Comment by mattjala** [comment]
`H5Tenum_nameof` fails if the size of the enum's name exceeds the size of the given buffer, or if the passed buffer for the name is NULL. Having its behavior match the `H5x_get_name` functions (return size of full name, even if it exceeds the given size, do this regardless of whether the given buffer exists) would be an API-breaking change, which probably isn't warranted, especially since the difference in the function names is a hint that it works differently. Closing for now.
