### ISSUE TITLE
Atomicity Test Failed Process 1: read_buf[2047] is 0, should be 5

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2196]
**Describe the bug**
See 

https://forum.hdfgroup.org/t/hdf5-1-12-1-make-check-atomiticity-test-failure/9701

**Expected behavior**

Pass test.

**Platform (please complete the following information)**
 - HDF5 version: 1.12.1 and develop
 - OS and version: Ubuntu 20.04 and latest
 - Compiler and version: gcc 
 - Build system (e.g. CMake, Autotools) and version: autotools
 - Any configure options you specified: --enable-parallel
 - MPI library and version (parallel HDF5): sudo apt-get libopenmpi-dev

**Additional context**

https://github.com/hyoklee/hdf5/actions/workflows/linux-auto.yml

**Comment by opoplawski** [comment]
I seem to be seeing a version of this on Fedora Rawhide with HDF5 1.12.1 and openmpi 4.1.5rc2 on ppc64le:
```
Atomicity Test Failed Process 2: read_buf[800] is 5, should be 0
Atomicity Test Failed Process 2: read_buf[801] is 5, should be 0
```
Build: https://copr.fedorainfracloud.org/coprs/orion/openmpi-4.1.5/build/5155430/

**Comment by jhendersonHDF** [comment]
Following through the related OpenMPI discussions, it's likely that these tests have always been succeeding in the past by chance. There are problem reports for failures in these tests back in the 1.8 branch as well. I think the solution for this issue is to add build system code that only runs the atomicity tests when the version of OpenMPI used supports the relevant atomicity functionality.
