### ISSUE TITLE
Provide a source and CMake option to disable Onion VFD.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2925]
**Is your feature request related to a problem? Please describe.**
I don't want to build & use Onion VFD.

**Describe the solution you'd like**
I want to see  an option`HDF5_ENABLE_ONION_VFD` like `HDF5_ENABLE_ROS3_VFD`.

**Describe alternatives you've considered**
Probably, `HDF5_ENABLE_VFD=ON/OFF`?

**Additional context**
Feature creep

**Comment by byrnHDF** [comment]
A build option must have a source option to change. There is not an option in the source.

**Comment by derobins** [comment]
I don't see a compelling argument for this change. If you don't use the onion VFD it won't significantly affect your code as there's no real run-time impact of it being present but unused.

if we add a configuration option to turn this off, however, there are definitely downsides:

* One more configuration that should be tested
* More ifdef soup in the code
* More configuration options that must be maintained (in two build systems!)

As for feature creep, that exists regardless of the presence of a configure option or not. If anything, the feature creep is *worse* with a configure option because the code and configuration become more complicated.
