### ISSUE TITLE
Clang -O4 Build Fails H5Tconv.c

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#4208]
Please check the new _Float16 code with the highest optimization levels for all compilers.

```
  "___truncxfhf2", referenced from:
      _H5T__conv_ldouble__Float16 in H5Tconv.c.o
ld: symbol(s) not found for architecture x86_64
```

See also: https://my.cdash.org/viewBuildError.php?buildid=2524289

**Comment by jhendersonHDF** [comment]
Was `clang` installed with homebrew on that machine? See https://github.com/JuliaLang/julia/issues/52067 which is almost certainly related.

**Comment by hyoklee** [comment]
I'm using built-in Apple /usr/bin/clang.

**Comment by chenrui333** [comment]
@jhendersonHDF I am still seeing the build failure with the 12 builds (full build log, https://github.com/Homebrew/homebrew-core/actions/runs/8973996030/job/24648320497), can I get some help on it?

relates to https://github.com/Homebrew/homebrew-core/pull/170959

**Comment by jhendersonHDF** [comment]
Hi @chenrui333,

several versions of AppleClang have been problematic due to having the type and macros for `_Float16` support while (I believe) having an issue with the version of compiler-rt used. If you're not necessarily interested in `_Float16` support, it can be disabled with the configure option `--disable-nonstandard-feature-float16` (Autotools) or `-DHDF5_ENABLE_NONSTANDARD_FEATURE_FLOAT16=OFF` (CMake). Otherwise, we can see if we can come up with a configure time check that will fully catch this on MacOS 12. I believe we were only using homebrew to install ninja on the MacOS 12 GitHub runner at the time this was tested, so there may be some differences between what was being tested.

While this particular GitHub issue dealt with compile failures in the library's main source code, it looks like your configure logs show that the library correctly picked up and built in `_Float16` support without failing any of the configure checks I added, but then fails when compiling the test code. I'm not sure why that would be.
