### ISSUE TITLE
How to compile this library for RISC-V with static linking?

### ISSUE THREAD

**Issue by EdrisBorne** [HDFGroup/hdf5#4727]
Hello,

Could you please give me some instructions what to change in the scripts and config files to compile the latest version of this repository for RISCV architecture?

I just added riscv.cmake in config/toolchain/ so far:

```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)


set(CMAKE_C_COMPILER riscv64-unknown-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER riscv64-unknown-linux-gnu-g++)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=rv64gc -mabi=lp64d")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=rv64gc -mabi=lp64d")

# Ensure static linking
set(BUILD_SHARED_LIBS OFF)


set(CMAKE_SYSROOT /home/user/Desktop/rv/compiler-install/sysroot )
#set(CMAKE_FIND_ROOT_PATH /home/user/Desktop/rv/compiler-install/sysroot )
```
and set the macros in configure.ac:
```
AC_SUBST([CFLAGS])
CFLAGS="${CFLAGS} -O2 -march=rv64gc -mabi=lp64d"

AC_PROG_CC
CC=riscv64-unknown-linux-gnu-gcc
CXX=riscv64-unknown-linux-gnu-g++
FC=riscv64-unknown-linux-gnu-gfortran


#also set this to yes
## Default is no
STATIC_EXEC=yes
```
After I run these:
```
./autogen.sh
./configure --prefix=/home/user/Desktop/riscv-hdf5 --host=riscv64-unknown-linux-gnu --host=riscv64-unknown-linux-gnu --enable-static=yes --enable-shared=no  --disable-hl
make
```
I get the following warning:

```
/home/user/Desktop/rv/compiler-install/lib/gcc/riscv64-unknown-linux-gnu/13.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: /home/user/Desktop/riscv-hdf5/src/.libs/libhdf5.a(H5PLint.o): in function `H5PL__open':
/home/user/Desktop/riscv-hdf5/src/H5PLint.c:346:(.text+0x5dc): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

How can I fix this?

Thanks a lot.

**Comment by derobins** [comment]
Hi,

First of all, you don't need to modify CMake files if you are going to build with the Autotools.

Second, you don't need to modify configure.ac. You can set CFLAGS on the command line, for example, and static executables can be set using the --enable-static-exec configure option.

The warning is because you are building fully statically linked executables. In the Autotools, this adds the "-all-static" libtool option, which will link everything statically, including glibc, and combining that with dlopen() (used in the library for loading plugins), is probably going to give you headaches. You can probably ignore it if you will never load a compression/VFD/VOL connector plugin, though.

For future reference, support questions should be asked on the HDF Group Forum (https://forum.hdfgroup.org/).

**Comment by hyoklee** [comment]
Hi, @EdrisBorne !

I tried the following:

`            cmake -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_STATIC_LIBS:BOOL=ON -DBUILD_STATIC_TOOLS:BOOL=ON ..`

It worked on my RISC-V GitHub Action test: 

https://github.com/hyoklee/actions/actions/runs/10514029221/workflow
