### ISSUE TITLE
Generate automatically non-versioned source packages to the release assets

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#4907]
The release procedure should automatically generate copies of the hdf5-x.x.x.tar.gz and hdf5-x.x.x.zip to hdf5.tar.gz and hdf5.zip. For 1.14.5, this had to be done manually, the same as for the 1.14.4 release.

**Comment by byrnHDF** [comment]
Snapshots should have the non-versioned files but I disagree that a release should have them - a release is version specific since it is a specific tag.

**Comment by brtnfld** [comment]
This only concerns an additional name package that does not include the version number. The contents themselves are self-evident about the library's version. My understanding was that we agreed to do this back in 1.14.4. Some CIs I have were changed to always point to the latest release, and 1.14.5 broke it before adding the files manually.

**Comment by byrnHDF** [comment]
My recollection was that it was only for snapshots, but that seems irrelevant since snapshot file are always the same; snapshot-1.14.  But then again, I guess if you get to the location through latest then you don't have the version info.
The CI was changed because the copy step failed except for snapshots. You can easily add the two files, now but I will need to debug the CI for release

**Comment by byrnHDF** [comment]
This has been fixed in the release workflow.
