### ISSUE TITLE
out-of-bounds read and write in vg_replace_strmem.c

### ISSUE THREAD

**Issue by guitos** [HDFGroup/hdf5#570]
Hi,

I'm from Red Hat Product Security and we received a CVE request to an issue in HDF5.

We asked the reporter to contact upstream for the CVE acknowledge before assigning a CVE but we didn't have any update from reporter since then.

The full bug report is already public and available here: https://github.com/winson2004aa/PAAFS/tree/master/vul1

Thanks.

**Comment by epourmal** [comment]
Thank you for reporting!

We will add this issue to our list of CVEs we have been working on.

Elena



On Apr 23, 2021, at 1:43 PM, Guilherme de Almeida Suckevicz ***@***.***> wrote:

﻿

Hi,

I'm from Red Hat Product Security and we received a CVE request to an issue in HDF5.

We asked the reporter to contact upstream for the CVE acknowledge before assigning a CVE but we didn't have any update from reporter since then.

The full bug report is already public and available here: https://github.com/winson2004aa/PAAFS/tree/master/vul1

Thanks.

**Comment by derobins** [comment]
Fixed in develop. h5dump exits with an error code (no segfault) and no memory leaks.
